#!/usr/bin/env bash
set -euo pipefail

# Install the dabba CLI:
#   curl -fsSL https://raw.githubusercontent.com/spice-labs-inc/dabba/main/install.sh | bash
#
# Downloads the prebuilt binary for your platform from the latest GitHub Release,
# installs it to ~/.local/bin, and wires up shell completions.

REPO="spice-labs-inc/dabba"
TARGET_DIR="${DABBA_INSTALL_DIR:-${HOME}/.local/bin}"
COMPLETION_DIR="${HOME}/.local/share/dabba/completions"

# ── Detect platform ──────────────────────────────────────────────────────────
os="$(uname -s)"
arch="$(uname -m)"
case "$os" in
  Linux)  plat_os="unknown-linux-musl" ;;
  Darwin) plat_os="apple-darwin" ;;
  *) echo "✗ unsupported OS: $os (use install.ps1 on Windows)" >&2; exit 1 ;;
esac
case "$arch" in
  x86_64|amd64)  plat_arch="x86_64" ;;
  aarch64|arm64) plat_arch="aarch64" ;;
  *) echo "✗ unsupported architecture: $arch" >&2; exit 1 ;;
esac
# macOS ships Apple Silicon binaries only; Intel Macs build from source.
if [ "$plat_os" = "apple-darwin" ] && [ "$plat_arch" = "x86_64" ]; then
  echo "✗ no prebuilt binary for Intel macOS." >&2
  echo "  Build from source: cargo install --git https://github.com/${REPO}" >&2
  exit 1
fi
target="${plat_arch}-${plat_os}"
url="https://github.com/${REPO}/releases/latest/download/dabba-${target}.tar.gz"

echo "📦 Installing dabba (${target}) to ${TARGET_DIR}"

# ── Download + verify + install the binary ───────────────────────────────────
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
archive="dabba-${target}.tar.gz"
if ! curl -fsSL "$url" -o "$tmp/$archive"; then
  echo "✗ could not download $url" >&2
  echo "  (no release asset for $target yet? see ${REPO}/releases)" >&2
  exit 1
fi
# Verify against the published SHA-256 checksum before trusting the binary.
if curl -fsSL "$url.sha256" -o "$tmp/$archive.sha256" 2>/dev/null; then
  if command -v sha256sum >/dev/null 2>&1; then sumcmd="sha256sum"; else sumcmd="shasum -a 256"; fi
  if ( cd "$tmp" && $sumcmd -c "$archive.sha256" >/dev/null 2>&1 ); then
    echo "✅ checksum verified"
  else
    echo "✗ checksum verification FAILED for $archive — refusing to install" >&2
    exit 1
  fi
else
  echo "⚠️  no published checksum for $archive — skipping verification"
fi
tar -xzf "$tmp/$archive" -C "$tmp"
mkdir -p "$TARGET_DIR"
install -m 0755 "$tmp/dabba" "$TARGET_DIR/dabba"
echo "✅ dabba $("$TARGET_DIR/dabba" --version 2>/dev/null | awk '{print $2}') installed"

# ── Shell completions (generated by the binary, always in sync) ──────────────
mkdir -p "$COMPLETION_DIR"
"$TARGET_DIR/dabba" completions bash > "$COMPLETION_DIR/dabba.bash" 2>/dev/null || true
BASH_LINE="[ -f \"$COMPLETION_DIR/dabba.bash\" ] && source \"$COMPLETION_DIR/dabba.bash\""
ZSH_BLOCK="autoload -U +X bashcompinit 2>/dev/null && bashcompinit 2>/dev/null
$BASH_LINE"
wired=0
for rc in "${HOME}/.bashrc" "${HOME}/.zshrc"; do
  [ -f "$rc" ] || continue
  case "$rc" in
    *.zshrc)
      grep -qF "$COMPLETION_DIR/dabba.bash" "$rc" 2>/dev/null \
        || printf '\n# dabba tab completion\n%s\n' "$ZSH_BLOCK" >> "$rc" ;;
    *)
      grep -qF "$COMPLETION_DIR/dabba.bash" "$rc" 2>/dev/null \
        || printf '\n# dabba tab completion\n%s\n' "$BASH_LINE" >> "$rc" ;;
  esac
  wired=1
done
[ "$wired" = 1 ] && echo "✅ Tab completion installed (restart your shell to activate)"

# ── PATH note ────────────────────────────────────────────────────────────────
if [[ ":$PATH:" != *":$TARGET_DIR:"* ]]; then
  echo "⚠️  ${TARGET_DIR} is not on your PATH. Add to your shell profile:"
  echo "     export PATH=\"\$PATH:$TARGET_DIR\""
fi

# ── Runtime prerequisites (dabba drives these) ───────────────────────────────
missing=""
for t in docker kubectl tofu; do command -v "$t" >/dev/null 2>&1 || missing="$missing $t"; done
if [ -n "$missing" ]; then
  echo "💡 dabba needs these on your PATH:${missing}"
  echo "   docker → https://docs.docker.com/get-docker/   tofu → https://opentofu.org/docs/intro/install/"
fi
echo "→ run 'dabba doctor' to check your setup, then 'dabba up' to bring up a platform"
