# Install the dabba CLI on Windows:
#   irm https://raw.githubusercontent.com/spice-labs-inc/dabba/main/install.ps1 | iex
#
# Downloads the prebuilt binary from the latest GitHub Release, installs it under
# %LOCALAPPDATA%\dabba\bin, and writes a PowerShell completion script.

$ErrorActionPreference = "Stop"

$Repo = "spice-labs-inc/dabba"

# Detect architecture (PROCESSOR_ARCHITECTURE is the process arch; the W6432 var
# is set when a 32-bit process runs on 64-bit Windows).
$arch = $env:PROCESSOR_ARCHITEW6432
if (-not $arch) { $arch = $env:PROCESSOR_ARCHITECTURE }
switch ($arch) {
    "ARM64" { $Target = "aarch64-pc-windows-msvc" }
    "AMD64" { $Target = "x86_64-pc-windows-msvc" }
    default { Write-Error "Unsupported architecture: $arch"; exit 1 }
}

$TargetDir = Join-Path $env:LOCALAPPDATA "dabba\bin"
$Url       = "https://github.com/$Repo/releases/latest/download/dabba-$Target.zip"

Write-Host "Installing dabba ($Target) to $TargetDir"

New-Item -ItemType Directory -Force -Path $TargetDir | Out-Null
$tmp = New-TemporaryFile
try {
    Invoke-WebRequest -Uri $Url -OutFile $tmp.FullName
    Expand-Archive -Path $tmp.FullName -DestinationPath $TargetDir -Force
} finally {
    Remove-Item $tmp.FullName -ErrorAction SilentlyContinue
}

$exe = Join-Path $TargetDir "dabba.exe"
Write-Host "Installed: $exe"

# PowerShell completion (generated by the binary, always in sync).
$ProfileDir = Split-Path -Parent $PROFILE
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
$Completion = Join-Path $ProfileDir "dabba.completion.ps1"
& $exe completions powershell | Out-File -FilePath $Completion -Encoding utf8
$SourceLine = ". `"$Completion`""
if (-not (Test-Path $PROFILE) -or -not (Select-String -Path $PROFILE -SimpleMatch $Completion -Quiet)) {
    Add-Content -Path $PROFILE -Value "`n# dabba tab completion`n$SourceLine"
    Write-Host "Tab completion installed (restart PowerShell to activate)"
}

# PATH note.
if ($env:Path -notlike "*$TargetDir*") {
    Write-Host "Add dabba to your PATH:"
    Write-Host "  [Environment]::SetEnvironmentVariable('Path', `$env:Path + ';$TargetDir', 'User')"
}

Write-Host "Run 'dabba doctor' to check your setup, then 'dabba up' to bring up a platform"
