terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = ">= 3.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.38"
    }
  }
}

variable "kubeconfig_path" {
  type = string
}

# cluster-vars, driven by the dabba CLI from the DabbaConfig (defaults preserve
# the local quickstart behavior).
variable "domain" {
  type    = string
  default = "localtest.me"
}
variable "cluster_issuer" {
  type    = string
  default = "dabba-ca"
}
variable "cluster_name" {
  type    = string
  default = "dabba"
}
variable "environment" {
  type    = string
  default = "local"
}
variable "sync_path" {
  type    = string
  default = "clusters/local"
}

# Cloud (EKS) cluster-vars. Empty on local; the dabba CLI fills them from the
# 01-cluster outputs so the cloud overlay's controllers can find their IRSA roles,
# the EFS filesystem, the VPC, and the delegated Route53 zone.
variable "region" {
  type    = string
  default = ""
}
variable "vpc_id" {
  type    = string
  default = ""
}
variable "route53_zone_id" {
  type    = string
  default = ""
}
variable "acme_email" {
  type    = string
  default = ""
}
variable "lb_controller_role_arn" {
  type    = string
  default = ""
}
variable "external_dns_role_arn" {
  type    = string
  default = ""
}
variable "cert_manager_role_arn" {
  type    = string
  default = ""
}

# Per-env secrets generated by the dabba CLI (secret-zero — no shipped defaults).
# Empty defaults only so `tofu destroy` has a value; `dabba up` always passes a real one.
variable "openbao_root_token" {
  type    = string
  default = ""
}
variable "forgejo_admin_password" {
  type    = string
  default = ""
}

provider "kubernetes" {
  config_path = var.kubeconfig_path
}

provider "helm" {
  kubernetes = {
    config_path = var.kubeconfig_path
  }
}

# In-cluster Forgejo — the authoritative git source. `dabba up` loads the gitops
# content into it after this applies (Flux retries the empty repo until then).
#
# NOTE: sources track main until the first tagged release, after which the
# quickstart pins a tag so it never breaks underneath a user.
module "git_server" {
  source = "git::https://github.com/spice-labs-inc/dabba-modules.git//modules/git-server?ref=main"

  persistence    = false # ephemeral for the local quickstart
  admin_password = var.forgejo_admin_password

  providers = {
    helm       = helm
    kubernetes = kubernetes
  }
}

# Installs the Flux Operator + a FluxInstance syncing from the in-cluster Forgejo,
# and stamps the cluster-vars ConfigMap. One apply, no kubernetes_manifest.
module "flux" {
  source = "git::https://github.com/spice-labs-inc/dabba-modules.git//modules/flux-operator?ref=main"

  gitops_repo_url = module.git_server.gitops_repo_url
  gitops_ref      = "refs/heads/main"
  sync_path       = var.sync_path

  cluster_vars = {
    domain                 = var.domain
    cluster_issuer         = var.cluster_issuer
    cluster                = var.cluster_name
    environment            = var.environment
    openbao_root_token     = var.openbao_root_token
    region                 = var.region
    vpc_id                 = var.vpc_id
    route53_zone_id        = var.route53_zone_id
    acme_email             = var.acme_email
    lb_controller_role_arn = var.lb_controller_role_arn
    external_dns_role_arn  = var.external_dns_role_arn
    cert_manager_role_arn  = var.cert_manager_role_arn
  }

  providers = {
    helm       = helm
    kubernetes = kubernetes
  }

  depends_on = [module.git_server]
}
